from flask import Flask, render_template, json

app = Flask(__name__)


@app.route("/")
def main():
    data = [['1990-03-26', 0.0825, 0.0842, 0.0816, 0.0842, 41702400],
            ['1990-03-27', 0.0833, 0.0859, 0.0825, 0.0859, 15926400],
            ['1990-03-28', 0.0859, 0.0859, 0.0851, 0.0851, 9792000],
            ['1990-03-29', 0.0851, 0.0851, 0.0833, 0.0851, 16272000],
            ['1990-03-30', 0.0833, 0.0833, 0.0799, 0.0816, 28742400],
            ['1990-04-02', 0.079, 0.0807, 0.0773, 0.0799, 15868800],
            ['1990-04-03', 0.079, 0.0816, 0.079, 0.0807, 8352000],
            ['1990-04-04', 0.0807, 0.0816, 0.0807, 0.0807, 14284800],
            ['1990-04-05', 0.0816, 0.0816, 0.0799, 0.0803, 8323200],
            ['1990-04-06', 0.0799, 0.0807, 0.079, 0.079, 10771200],
            ['1990-04-09', 0.0799, 0.0799, 0.0781, 0.0781, 6681600],
            ['1990-04-10', 0.0781, 0.0799, 0.0746, 0.0764, 34790400],
            ['1990-04-11', 0.0764, 0.0773, 0.0755, 0.0764, 24796800],
            ['1990-04-12', 0.0773, 0.0773, 0.0755, 0.0773, 13161600],
            ['1990-04-16', 0.0773, 0.0781, 0.0764, 0.0773, 5616000],
            ['1990-04-17', 0.0764, 0.0781, 0.0755, 0.0781, 6566400],
            ['1990-04-18', 0.0781, 0.0799, 0.0773, 0.079, 24480000],
            ['1990-04-19', 0.0781, 0.0799, 0.0781, 0.0799, 25142400],
            ['1990-04-20', 0.0799, 0.0799, 0.0773, 0.0773, 8755200],
            ['1990-04-23', 0.0773, 0.079, 0.0764, 0.0781, 5356800],
            ['1990-04-24', 0.0799, 0.0799, 0.079, 0.0794, 10281600],
            ['1990-04-25', 0.0799, 0.0807, 0.0799, 0.0799, 6768000],
            ['1990-04-26', 0.0799, 0.0816, 0.0799, 0.0799, 10713600],
            ['1990-04-27', 0.0799, 0.0807, 0.079, 0.079, 4204800],
            ['1990-04-30', 0.0807, 0.0842, 0.0799, 0.0825, 34329600],
            ['1990-05-01', 0.0842, 0.0842, 0.0825, 0.0838, 28771200],
            ['1990-05-02', 0.0833, 0.0842, 0.0825, 0.0825, 3139200],
            ['1990-05-03', 0.0842, 0.0851, 0.0833, 0.0851, 7228800],
            ['1990-05-04', 0.0842, 0.0859, 0.0842, 0.0859, 5702400],
            ['1990-05-07', 0.0859, 0.0885, 0.0859, 0.0868, 13536000],
            ['1990-05-08', 0.0885, 0.0885, 0.0859, 0.0877, 14486400],
            ['1990-05-09', 0.0877, 0.0877, 0.0851, 0.0859, 9676800],
            ['1990-05-10', 0.0868, 0.0868, 0.0851, 0.0851, 2793600],
            ['1990-05-11', 0.0885, 0.0894, 0.0851, 0.0859, 29923200],
            ['1990-05-14', 0.0877, 0.0877, 0.0859, 0.0859, 15235200],
            ['1990-05-15', 0.0877, 0.0877, 0.0859, 0.0864, 24134400],
            ['1990-05-16', 0.0877, 0.0877, 0.0851, 0.0859, 18720000],
            ['1990-05-17', 0.0868, 0.0868, 0.0859, 0.0868, 6595200],
            ['1990-05-18', 0.0859, 0.0868, 0.0842, 0.0851, 45417600],
            ['1990-05-21', 0.0842, 0.0868, 0.0842, 0.0851, 4032000],
            ['1990-05-22', 0.0851, 0.0859, 0.0851, 0.0851, 22982400],
            ['1990-05-23', 0.0851, 0.0859, 0.0842, 0.0842, 39715200],
            ['1990-05-24', 0.0859, 0.0859, 0.0842, 0.0859, 8121600],
            ['1990-05-25', 0.0833, 0.0851, 0.0825, 0.0833, 4003200],
            ['1990-05-29', 0.0833, 0.0851, 0.0816, 0.0825, 20707200],
            ['1990-05-30', 0.0833, 0.0833, 0.0807, 0.0816, 96278400],
            ['1990-05-31', 0.0807, 0.0868, 0.0807, 0.0859, 102988800],
            ['1990-06-01', 0.0859, 0.0885, 0.0851, 0.0868, 103132800],
            ['1990-06-04', 0.0877, 0.0894, 0.0859, 0.0894, 48499200],
            ['1990-06-05', 0.0885, 0.0938, 0.0885, 0.0929, 56131200],
            ['1990-06-06', 0.0929, 0.0929, 0.0903, 0.092, 23241600],
            ['1990-06-07', 0.0929, 0.0929, 0.0885, 0.0894, 18144000],
            ['1990-06-08', 0.0903, 0.0903, 0.0868, 0.0877, 6566400],
            ['1990-06-11', 0.0851, 0.0877, 0.0851, 0.0872, 3686400],
            ['1990-06-12', 0.0877, 0.0972, 0.0868, 0.0955, 133401600],
            ['1990-06-13', 0.0972, 0.0972, 0.0963, 0.0963, 52099200],
            ['1990-06-14', 0.0972, 0.0981, 0.0955, 0.0972, 54374400],
            ['1990-06-15', 0.0955, 0.0972, 0.0955, 0.0955, 6537600],
            ['1990-06-18', 0.0972, 0.0972, 0.092, 0.0938, 11923200],
            ['1990-06-19', 0.0903, 0.0929, 0.0903, 0.0929, 20851200],
            ['1990-06-20', 0.0929, 0.0946, 0.092, 0.0938, 30124800],
            ['1990-06-21', 0.0929, 0.0946, 0.092, 0.0946, 9936000],
            ['1990-06-22', 0.0946, 0.0946, 0.0929, 0.0946, 806400],
            ['1990-06-25', 0.0946, 0.0946, 0.0929, 0.0933, 3600000],
            ['1990-06-26', 0.0929, 0.0938, 0.0903, 0.092, 4665600],
            ['1990-06-27', 0.0929, 0.0929, 0.0903, 0.092, 3801600],
            ['1990-06-28', 0.0903, 0.092, 0.0868, 0.0912, 153648000],
            ['1990-06-29', 0.0912, 0.092, 0.0903, 0.092, 48268800],
            ['1990-07-02', 0.092, 0.0938, 0.0903, 0.0929, 38131200],
            ['1990-07-03', 0.092, 0.0938, 0.092, 0.0929, 2851200],
            ['1990-07-05', 0.092, 0.092, 0.0903, 0.0916, 6508800],
            ['1990-07-06', 0.0903, 0.0916, 0.0903, 0.0916, 2476800],
            ['1990-07-09', 0.0916, 0.092, 0.0903, 0.0912, 14630400],
            ['1990-07-10', 0.0929, 0.0938, 0.0912, 0.0938, 41529600],
            ['1990-07-11', 0.0938, 0.0963, 0.0929, 0.0955, 32515200],
            ['1990-07-12', 0.0963, 0.0998, 0.0955, 0.0998, 16617600],
            ['1990-07-13', 0.0981, 0.105, 0.0981, 0.105, 46627200],
            ['1990-07-16', 0.1042, 0.105, 0.1007, 0.1024, 79977600],
            ['1990-07-17', 0.1016, 0.1024, 0.0946, 0.0972, 42019200],
            ['1990-07-18', 0.0946, 0.0998, 0.0946, 0.099, 23529600],
            ['1990-07-19', 0.0981, 0.0998, 0.0972, 0.0972, 25804800],
            ['1990-07-20', 0.0981, 0.0981, 0.0963, 0.0972, 60192000],
            ['1990-07-23', 0.0972, 0.0972, 0.0912, 0.0912, 35913600],
            ['1990-07-24', 0.092, 0.092, 0.0825, 0.0859, 51264000],
            ['1990-07-25', 0.0842, 0.0894, 0.0842, 0.0885, 43718400],
            ['1990-07-26', 0.0885, 0.0912, 0.0885, 0.0903, 17740800],
            ['1990-07-27', 0.0912, 0.0912, 0.0894, 0.0894, 8841600],
            ['1990-07-30', 0.0894, 0.0903, 0.0877, 0.0903, 17856000],
            ['1990-07-31', 0.0903, 0.0903, 0.0885, 0.0885, 9331200],
            ['1990-08-01', 0.0885, 0.0885, 0.0868, 0.0885, 8409600],
            ['1990-08-02', 0.0877, 0.0877, 0.0842, 0.0868, 6163200],
            ['1990-08-03', 0.0859, 0.0859, 0.0799, 0.0842, 54460800],
            ['1990-08-06', 0.0842, 0.0851, 0.079, 0.0833, 62150400],
            ['1990-08-07', 0.0851, 0.0868, 0.0833, 0.0846, 36115200],
            ['1990-08-08', 0.0851, 0.0859, 0.0833, 0.0833, 21916800],
            ['1990-08-09', 0.0842, 0.0885, 0.0833, 0.0877, 50803200],
            ['1990-08-10', 0.0868, 0.0885, 0.0825, 0.0833, 35193600],
            ['1990-08-13', 0.0816, 0.0825, 0.0799, 0.082, 12931200],
            ['1990-08-14', 0.0807, 0.0825, 0.0807, 0.0807, 21945600],
            ['1990-08-15', 0.0825, 0.0825, 0.0807, 0.0825, 35856000],
            ['1990-08-16', 0.0812, 0.0825, 0.0807, 0.0807, 21744000],
            ['1990-08-17', 0.0816, 0.0859, 0.0799, 0.0859, 88185600],
            ['1990-08-20', 0.0859, 0.0885, 0.0851, 0.0859, 45417600],
            ['1990-08-21', 0.0842, 0.0851, 0.0807, 0.0816, 36720000],
            ['1990-08-22', 0.0842, 0.0851, 0.0833, 0.0842, 26409600],
            ['1990-08-23', 0.0799, 0.0816, 0.0764, 0.0781, 56678400],
            ['1990-08-24', 0.0799, 0.0833, 0.079, 0.0825, 59011200],
            ['1990-08-27', 0.0851, 0.0885, 0.0851, 0.0877, 36720000],
            ['1990-08-28', 0.0868, 0.0877, 0.0859, 0.0868, 19843200],
            ['1990-08-29', 0.0859, 0.0868, 0.0833, 0.0859, 49737600],
            ['1990-08-30', 0.0859, 0.0872, 0.0842, 0.0859, 45590400],
            ['1990-08-31', 0.0859, 0.0877, 0.0859, 0.0859, 12182400],
            ['1990-09-04', 0.0859, 0.0877, 0.0851, 0.0859, 26236800],
            ['1990-09-05', 0.0877, 0.0877, 0.0859, 0.0868, 36720000],
            ['1990-09-06', 0.0859, 0.0868, 0.0833, 0.0842, 37209600],
            ['1990-09-07', 0.0851, 0.0868, 0.0842, 0.0868, 16300800],
            ['1990-09-10', 0.0868, 0.0877, 0.0851, 0.0859, 40204800],
            ['1990-09-11', 0.0859, 0.0877, 0.0859, 0.0859, 11894400],
            ['1990-09-12', 0.0859, 0.0868, 0.0859, 0.0868, 13305600],
            ['1990-09-13', 0.0877, 0.0877, 0.0859, 0.0859, 20966400],
            ['1990-09-14', 0.0859, 0.0877, 0.0859, 0.0859, 16819200],
            ['1990-09-17', 0.0868, 0.0903, 0.0859, 0.0903, 89712000],
            ['1990-09-18', 0.0903, 0.0938, 0.0885, 0.0929, 33667200],
            ['1990-09-19', 0.0938, 0.0938, 0.0877, 0.0885, 74073600],
            ['1990-09-20', 0.0877, 0.0898, 0.0877, 0.0885, 75571200],
            ['1990-09-21', 0.0885, 0.0885, 0.0851, 0.0859, 60969600],
            ['1990-09-24', 0.0842, 0.0851, 0.0825, 0.0842, 96278400],
            ['1990-09-25', 0.0825, 0.0859, 0.0825, 0.0851, 115718400],
            ['1990-09-26', 0.0859, 0.0859, 0.0825, 0.0825, 64512000],
            ['1990-09-27', 0.0833, 0.0842, 0.0773, 0.0785, 74073600],
            ['1990-09-28', 0.0773, 0.0781, 0.0755, 0.0781, 155030400],
            ['1990-10-01', 0.0781, 0.0851, 0.0781, 0.0842, 89596800],
            ['1990-10-02', 0.0868, 0.0877, 0.0825, 0.0833, 48441600],
            ['1990-10-03', 0.0825, 0.0842, 0.0807, 0.0807, 61459200],
            ['1990-10-04', 0.0807, 0.0833, 0.0807, 0.0833, 23385600],
            ['1990-10-05', 0.0799, 0.0842, 0.0799, 0.0816, 43401600],
            ['1990-10-08', 0.0851, 0.0851, 0.0825, 0.0829, 10598400],
            ['1990-10-09', 0.0825, 0.0833, 0.0755, 0.0773, 115027200],
            ['1990-10-10', 0.0729, 0.0738, 0.0686, 0.0712, 113241600],
            ['1990-10-11', 0.0703, 0.0729, 0.0694, 0.0712, 70041600],
            ['1990-10-12', 0.0738, 0.0777, 0.072, 0.0755, 41241600],
            ['1990-10-15', 0.0781, 0.0799, 0.0746, 0.0751, 59270400],
            ['1990-10-16', 0.0773, 0.0825, 0.0773, 0.0799, 61632000],
            ['1990-10-17', 0.0816, 0.0868, 0.0799, 0.0842, 50515200],
            ['1990-10-18', 0.0859, 0.092, 0.0851, 0.092, 121305600],
            ['1990-10-19', 0.0981, 0.1011, 0.0972, 0.0998, 241171200],
            ['1990-10-22', 0.1007, 0.1033, 0.0998, 0.1033, 127843200],
            ['1990-10-23', 0.1033, 0.1068, 0.1016, 0.1054, 102326400],
            ['1990-10-24', 0.1033, 0.1094, 0.1016, 0.1085, 66297600],
            ['1990-10-25', 0.1094, 0.1111, 0.1076, 0.1085, 83088000],
            ['1990-10-26', 0.1076, 0.1076, 0.1007, 0.1007, 94003200],
            ['1990-10-29', 0.1007, 0.1016, 0.0963, 0.0972, 37785600],
            ['1990-10-30', 0.0972, 0.1007, 0.092, 0.099, 90633600],
            ['1990-10-31', 0.1016, 0.105, 0.1007, 0.1024, 81244800],
            ['1990-11-01', 0.1007, 0.1024, 0.0998, 0.1024, 35971200],
            ['1990-11-02', 0.1024, 0.105, 0.1016, 0.105, 27648000],
            ['1990-11-05', 0.105, 0.1094, 0.1033, 0.1085, 37324800],
            ['1990-11-06', 0.1094, 0.112, 0.1085, 0.1102, 35827200],
            ['1990-11-07', 0.1107, 0.1107, 0.1042, 0.1042, 118022400],
            ['1990-11-08', 0.112, 0.1259, 0.1111, 0.1176, 701654400]]
    chart = {"chart":
        {
            "container": "container",
            "series": [
                {"enabled": True,
                 "seriesType": "candlestick",
                 "data": data
                 }],
            "Scroller": [
                {"enabled": True,
                 "type": "line",

                 }],
            "title": "Candlestick Chart",
            "type": "line",

            "enabled": True, "title": {"zIndex": 80, "enabled": False, "fontSize": 16,
                                       "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                       "fontColor": "#7c868e", "fontOpacity": 1,
                                       "fontDecoration": "none", "fontStyle": "normal",
                                       "fontVariant": "normal", "fontWeight": "normal",
                                       "letterSpacing": "normal", "textDirection": "ltr",
                                       "lineHeight": "normal", "textIndent": 0,
                                       "vAlign": "top", "hAlign": "center",
                                       "wordWrap": "normal", "wordBreak": "normal",
                                       "textOverflow": "", "selectable": False,
                                       "disablePointerEvents": False, "useHtml": False,
                                       "align": "center", "text": "Chart Title",
                                       "padding": {"left": 0, "top": 0, "bottom": 10,
                                                   "right": 0},
                                       "background": {"zIndex": 0, "enabled": False,
                                                      "fill": "#ffffff", "stroke": "none",
                                                      "cornerType": "round", "corners": 0}},
            "background": {"zIndex": 1, "enabled": True, "fill": "#ffffff", "stroke": "none",
                           "cornerType": "round", "corners": 0}, "margin": {},
            "padding": {"left": 60, "top": 20, "bottom": 56, "right": 30},
            "a11y": {"enabled": True, "mode": "chart-elements"}, "autoRedraw": True,
            "bounds": {}, "animation": {"enabled": False, "duration": 1000},
            "tooltip": {"zIndex": 0, "enabled": True, "minFontSize": 9, "maxFontSize": 13,
                        "adjustFontSize": {"width": False, "height": False}, "fontSize": 12,
                        "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                        "fontColor": "#ffffff", "fontOpacity": 1, "fontDecoration": "none",
                        "fontStyle": "normal", "fontVariant": "normal", "fontWeight": "normal",
                        "letterSpacing": "normal", "textDirection": "ltr",
                        "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                        "hAlign": "start", "wordWrap": "normal", "wordBreak": "normal",
                        "textOverflow": "", "selectable": False, "disablePointerEvents": False,
                        "useHtml": False, "width": None, "height": None,
                        "unionFormat": "{%joinedFormattedValues}", "valuePrefix": "",
                        "valuePostfix": "", "position": "left-top", "anchor": "left-top",
                        "offsetX": 10, "offsetY": 10, "allowLeaveScreen": True,
                        "allowLeaveChart": True, "allowLeaveStage": False,
                        "displayMode": "union", "positionMode": "float",
                        "title": {"zIndex": 1, "enabled": True, "fontSize": 13,
                                  "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                  "fontColor": "#ffffff", "fontOpacity": 1,
                                  "fontDecoration": "none", "fontStyle": "normal",
                                  "fontVariant": "normal", "fontWeight": "normal",
                                  "letterSpacing": "normal", "textDirection": "ltr",
                                  "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                                  "hAlign": "left", "wordWrap": "normal",
                                  "wordBreak": "normal", "textOverflow": "",
                                  "selectable": False, "disablePointerEvents": False,
                                  "useHtml": False, "width": None, "height": None,
                                  "align": "left", "orientation": "top", "rotation": 0,
                                  "text": "", "background": {"enabled": False, "fill": "none",
                                                             "stroke": "none",
                                                             "cornerType": "round",
                                                             "corners": 0}},
                        "separator": {"zIndex": 1, "enabled": True,
                                      "fill": {"color": "#CECECE", "opacity": 0.3},
                                      "stroke": "none", "width": "100%", "height": 1,
                                      "orientation": "top",
                                      "margin": {"left": 0, "top": 5, "bottom": 5,
                                                 "right": 0}},
                        "background": {"zIndex": 0, "enabled": True,
                                       "fill": {"color": "#212121", "opacity": 0.7},
                                       "stroke": "none", "cornerType": "round"},
                        "padding": {"left": 10, "top": 5, "bottom": 5, "right": 10},
                        "hideDelay": 0}, "contextMenu": {"enabled": True},
            "credits": {"text": "AnyChart",
                        "url": "https://www.anychart.com/?utm_source=registered",
                        "alt": "AnyChart - JavaScript Charts designed to be embedded and integrated{{anychart-version}}",
                        "imgAlt": "AnyChart - JavaScript Charts",
                        "logoSrc": "https://static.anychart.com/logo.png", "enabled": False},
            "selectMarqueeFill": {"color": "#d3d3d3", "opacity": 0.4},
            "selectMarqueeStroke": "#d3d3d3", "grouping": {"enabled": True, "forced": False,
                                                           "levels": [{"unit": "millisecond",
                                                                       "count": 1},
                                                                      {"unit": "millisecond",
                                                                       "count": 5},
                                                                      {"unit": "millisecond",
                                                                       "count": 10},
                                                                      {"unit": "millisecond",
                                                                       "count": 25},
                                                                      {"unit": "millisecond",
                                                                       "count": 50},
                                                                      {"unit": "millisecond",
                                                                       "count": 100},
                                                                      {"unit": "millisecond",
                                                                       "count": 250},
                                                                      {"unit": "millisecond",
                                                                       "count": 500},
                                                                      {"unit": "second",
                                                                       "count": 1},
                                                                      {"unit": "second",
                                                                       "count": 5},
                                                                      {"unit": "second",
                                                                       "count": 10},
                                                                      {"unit": "second",
                                                                       "count": 20},
                                                                      {"unit": "second",
                                                                       "count": 30},
                                                                      {"unit": "minute",
                                                                       "count": 1},
                                                                      {"unit": "minute",
                                                                       "count": 5},
                                                                      {"unit": "minute",
                                                                       "count": 15},
                                                                      {"unit": "minute",
                                                                       "count": 30},
                                                                      {"unit": "hour",
                                                                       "count": 1},
                                                                      {"unit": "hour",
                                                                       "count": 2},
                                                                      {"unit": "hour",
                                                                       "count": 6},
                                                                      {"unit": "hour",
                                                                       "count": 12},
                                                                      {"unit": "day",
                                                                       "count": 1},
                                                                      {"unit": "week",
                                                                       "count": 1},
                                                                      {"unit": "month",
                                                                       "count": 1},
                                                                      {"unit": "month",
                                                                       "count": 3},
                                                                      {"unit": "month",
                                                                       "count": 6},
                                                                      {"unit": "year",
                                                                       "count": 1}],
                                                           "maxVisiblePoints": 500,
                                                           "minPixPerPoint": None},
            "scrollerGrouping": {"enabled": True, "forced": False,
                                 "levels": [{"unit": "millisecond", "count": 1},
                                            {"unit": "millisecond", "count": 2},
                                            {"unit": "millisecond", "count": 5},
                                            {"unit": "millisecond", "count": 10},
                                            {"unit": "millisecond", "count": 25},
                                            {"unit": "millisecond", "count": 50},
                                            {"unit": "millisecond", "count": 100},
                                            {"unit": "millisecond", "count": 250},
                                            {"unit": "millisecond", "count": 500},
                                            {"unit": "second", "count": 1},
                                            {"unit": "second", "count": 2},
                                            {"unit": "second", "count": 5},
                                            {"unit": "second", "count": 10},
                                            {"unit": "second", "count": 20},
                                            {"unit": "second", "count": 30},
                                            {"unit": "minute", "count": 1},
                                            {"unit": "minute", "count": 2},
                                            {"unit": "minute", "count": 5},
                                            {"unit": "minute", "count": 10},
                                            {"unit": "minute", "count": 20},
                                            {"unit": "minute", "count": 30},
                                            {"unit": "hour", "count": 1},
                                            {"unit": "hour", "count": 2},
                                            {"unit": "hour", "count": 3},
                                            {"unit": "hour", "count": 4},
                                            {"unit": "hour", "count": 6},
                                            {"unit": "hour", "count": 12},
                                            {"unit": "day", "count": 1},
                                            {"unit": "day", "count": 2},
                                            {"unit": "day", "count": 4},
                                            {"unit": "week", "count": 1},
                                            {"unit": "week", "count": 2},
                                            {"unit": "month", "count": 1},
                                            {"unit": "month", "count": 2},
                                            {"unit": "month", "count": 3},
                                            {"unit": "month", "count": 6},
                                            {"unit": "year", "count": 1}],
                                 "maxVisiblePoints": None, "minPixPerPoint": 1}, "xScale": {},
            "scroller": {"zIndex": 40, "enabled": True, "height": 40, "orientation": "bottom",
                         "inverted": False, "autoHide": False, "fill": "none",
                         "selectedFill": {"color": "#1976d2", "opacity": 0.2},
                         "outlineStroke": "#cecece", "allowRangeChange": True,
                         "thumbs": {"normal": {"fill": "#E9E9E9", "stroke": "#7c868e"},
                                    "hovered": {"fill": "#ffffff", "stroke": "#757575"},
                                    "enabled": True, "autoHide": False},
                         "defaultSeriesType": "line", "palette": {"type": "distinct",
                                                                  "items": ["#64b5f6",
                                                                            "#1976d2",
                                                                            "#ef6c00",
                                                                            "#ffd54f",
                                                                            "#455a64",
                                                                            "#96a6a6",
                                                                            "#dd2c00",
                                                                            "#00838f",
                                                                            "#00bfa5",
                                                                            "#ffa000"]},
                         "hatchFillPalette": {"items": [
                             {"type": "backward-diagonal", "color": "black 0.5",
                              "thickness": 1, "size": 10},
                             {"type": "forward-diagonal", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "horizontal", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "vertical", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "dashed-backward-diagonal", "color": "black 0.5",
                              "thickness": 1, "size": 10},
                             {"type": "grid", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "dashed-forward-diagonal", "color": "black 0.5",
                              "thickness": 1, "size": 10},
                             {"type": "dashed-horizontal", "color": "black 0.5",
                              "thickness": 1, "size": 10},
                             {"type": "dashed-vertical", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "diagonal-cross", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "diagonal-brick", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "divot", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "horizontal-brick", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "vertical-brick", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "checker-board", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "confetti", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "plaid", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "solid-diamond", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "zig-zag", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "weave", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-05", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-10", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-20", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-25", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-30", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-40", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-50", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-60", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-70", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-75", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-80", "color": "black 0.5", "thickness": 1,
                              "size": 10},
                             {"type": "percent-90", "color": "black 0.5", "thickness": 1,
                              "size": 10}]}}, "plots": [
            {"zIndex": 10, "enabled": True, "maxPointWidth": "100%", "minPointLength": 0,
             "baseline": 0, "yScale": 0, "defaultSeriesType": "line",
             "background": {"zIndex": 1, "enabled": False, "fill": "#ffffff", "stroke": "none",
                            "cornerType": "round", "corners": 0},
             "title": {"zIndex": 80, "enabled": False, "fontSize": 12,
                       "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                       "fontColor": "#7c868e", "fontOpacity": 1, "fontDecoration": "none",
                       "fontStyle": "normal", "fontVariant": "normal", "fontWeight": "normal",
                       "letterSpacing": "normal", "textDirection": "ltr",
                       "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                       "hAlign": "center", "wordWrap": "normal", "wordBreak": "normal",
                       "textOverflow": "", "selectable": False, "disablePointerEvents": False,
                       "useHtml": False, "width": None, "height": None, "align": "center",
                       "text": "Plot Title",
                       "padding": {"left": 5, "top": 5, "bottom": 2, "right": 5},
                       "background": {"zIndex": 0, "enabled": False, "fill": "#ffffff",
                                      "stroke": "none", "cornerType": "round", "corners": 0}},
             "noDataLabel": {"zIndex": 999999, "enabled": False, "fontSize": 15,
                             "fontFamily": "Arial", "fontColor": "black", "fontOpacity": 1,
                             "fontDecoration": "none", "fontStyle": "normal",
                             "fontVariant": "normal", "fontWeight": "bold",
                             "letterSpacing": "normal", "textDirection": "ltr",
                             "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                             "hAlign": "start", "wordWrap": "normal", "wordBreak": "normal",
                             "textOverflow": "", "selectable": False,
                             "disablePointerEvents": False, "useHtml": False,
                             "text": "No data.", "position": "center", "width": None,
                             "height": None, "anchor": "center", "offsetX": 0, "offsetY": 0,
                             "rotation": 0,
                             "adjustFontSize": {"width": False, "height": False},
                             "minFontSize": 8, "maxFontSize": 72,
                             "background": {"zIndex": 0, "enabled": False, "fill": "#ffffff",
                                            "stroke": "none", "disablePointerEvents": False,
                                            "cornerType": "round"},
                             "padding": {"left": 0, "top": 0, "bottom": 0, "right": 0}},
             "dataArea": {"zIndex": 10, "enabled": True,
                          "background": {"enabled": False, "fill": "none", "stroke": "none",
                                         "cornerType": "round"}},
             "xAxis": {"zIndex": 35, "enabled": True, "height": 25,
                       "labels": {"zIndex": 35, "enabled": True,
                                  "background": {"enabled": False, "fill": "#ffffff",
                                                 "stroke": "none", "cornerType": "round"},
                                  "padding": {"left": 5, "top": 5, "bottom": 5, "right": 5},
                                  "minFontSize": 8, "maxFontSize": 72,
                                  "adjustFontSize": {"width": False, "height": False},
                                  "fontSize": "11px",
                                  "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                  "fontColor": "#7c868e", "fontOpacity": 1,
                                  "fontDecoration": "none", "fontStyle": "normal",
                                  "fontVariant": "normal", "fontWeight": "normal",
                                  "letterSpacing": "normal", "textDirection": "ltr",
                                  "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                                  "hAlign": "start", "wordWrap": "normal",
                                  "wordBreak": "normal", "textOverflow": "",
                                  "selectable": False, "disablePointerEvents": False,
                                  "useHtml": False, "position": "outside",
                                  "anchor": "center-top", "offsetX": 0, "offsetY": 0,
                                  "rotation": 0, "width": None, "height": None, "clip": None},
                       "minorLabels": {"zIndex": 35, "enabled": True,
                                       "background": {"enabled": False, "fill": "#ffffff",
                                                      "stroke": "none", "cornerType": "round"},
                                       "padding": {"left": 0, "top": 5, "bottom": 5,
                                                   "right": 0}, "minFontSize": 8,
                                       "maxFontSize": 72,
                                       "adjustFontSize": {"width": False, "height": False},
                                       "fontSize": "11px",
                                       "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                       "fontColor": "#7c868e", "fontOpacity": 1,
                                       "fontDecoration": "none", "fontStyle": "normal",
                                       "fontVariant": "normal", "fontWeight": "normal",
                                       "letterSpacing": "normal", "textDirection": "ltr",
                                       "lineHeight": "normal", "textIndent": 0,
                                       "vAlign": "top", "hAlign": "start",
                                       "wordWrap": "normal", "wordBreak": "normal",
                                       "textOverflow": "", "selectable": False,
                                       "disablePointerEvents": False, "useHtml": False,
                                       "position": "outside", "anchor": "center-top",
                                       "offsetX": 0, "offsetY": 0, "rotation": 0,
                                       "width": None, "height": None, "clip": None},
                       "ticks": {"zIndex": 35, "enabled": False, "stroke": "#CECECE",
                                 "length": 25, "position": "center"},
                       "minorTicks": {"zIndex": 35, "enabled": False, "stroke": "#EAEAEA",
                                      "length": 25, "position": "outside"},
                       "background": {"enabled": False, "fill": "#F7F7F7", "stroke": "#cecece",
                                      "cornerType": "round", "corners": 0},
                       "showHelperLabel": True, "overlapMode": "no-overlap"},
             "palette": {"type": "distinct",
                         "items": ["#64b5f6", "#1976d2", "#ef6c00", "#ffd54f", "#455a64",
                                   "#96a6a6", "#dd2c00", "#00838f", "#00bfa5", "#ffa000"]},
             "markerPalette": {
                 "items": ["circle", "diamond", "square", "triangle-down", "triangle-up",
                           "diagonal-cross", "pentagon", "cross", "v-line", "star5", "star4",
                           "trapezium", "star7", "star6", "star10"]}, "hatchFillPalette": {
                "items": [{"type": "backward-diagonal", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "forward-diagonal", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "horizontal", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "vertical", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "dashed-backward-diagonal", "color": "black 0.5",
                           "thickness": 1, "size": 10},
                          {"type": "grid", "color": "black 0.5", "thickness": 1, "size": 10},
                          {"type": "dashed-forward-diagonal", "color": "black 0.5",
                           "thickness": 1, "size": 10},
                          {"type": "dashed-horizontal", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "dashed-vertical", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "diagonal-cross", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "diagonal-brick", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "divot", "color": "black 0.5", "thickness": 1, "size": 10},
                          {"type": "horizontal-brick", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "vertical-brick", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "checker-board", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "confetti", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "plaid", "color": "black 0.5", "thickness": 1, "size": 10},
                          {"type": "solid-diamond", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "zig-zag", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "weave", "color": "black 0.5", "thickness": 1, "size": 10},
                          {"type": "percent-05", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-10", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-20", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-25", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-30", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-40", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-50", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-60", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-70", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-75", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-80", "color": "black 0.5", "thickness": 1,
                           "size": 10},
                          {"type": "percent-90", "color": "black 0.5", "thickness": 1,
                           "size": 10}]}, "crosshair": {"zIndex": 201, "enabled": True,
                                                        "xLabels": [
                                                            {"enabled": True, "background": {},
                                                             "padding": {}, "axisIndex": 0}],
                                                        "yLabels": [
                                                            {"enabled": True, "background": {},
                                                             "padding": {}, "axisIndex": 0}]},
             "yAxes": [{"zIndex": 35, "enabled": True,
                        "title": {"zIndex": 35, "enabled": False, "fontSize": 13,
                                  "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                  "fontColor": "#545f69", "fontOpacity": 1,
                                  "fontDecoration": "none", "fontStyle": "normal",
                                  "fontVariant": "normal", "fontWeight": "normal",
                                  "letterSpacing": "normal", "textDirection": "ltr",
                                  "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                                  "hAlign": "center", "wordWrap": "normal",
                                  "wordBreak": "normal", "textOverflow": "",
                                  "selectable": False, "disablePointerEvents": False,
                                  "useHtml": False, "align": "center", "text": "Y-Axis",
                                  "padding": {"left": 5, "top": 5, "bottom": 5, "right": 5},
                                  "background": {"enabled": False, "fill": "#ffffff",
                                                 "stroke": "none", "cornerType": "round",
                                                 "corners": 0}},
                        "labels": {"zIndex": 35, "enabled": True,
                                   "background": {"enabled": False, "fill": "#ffffff",
                                                  "stroke": "none", "cornerType": "round",
                                                  "corners": 0},
                                   "padding": {"left": 5, "top": 0, "bottom": 0, "right": 5},
                                   "minFontSize": 8, "maxFontSize": 72,
                                   "adjustFontSize": {"width": False, "height": False},
                                   "fontSize": "11px",
                                   "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                   "fontColor": "#7c868e", "fontOpacity": 1,
                                   "fontDecoration": "none", "fontStyle": "normal",
                                   "fontVariant": "normal", "fontWeight": "normal",
                                   "letterSpacing": "normal", "textDirection": "ltr",
                                   "lineHeight": "normal", "textIndent": 0, "vAlign": "top",
                                   "hAlign": "start", "wordWrap": "normal",
                                   "wordBreak": "normal", "textOverflow": "",
                                   "selectable": False, "disablePointerEvents": False,
                                   "useHtml": False, "position": "outside", "anchor": "center",
                                   "offsetX": 0, "offsetY": 0, "rotation": 0},
                        "minorLabels": {"zIndex": 35, "enabled": False,
                                        "background": {"enabled": False, "fill": "#ffffff",
                                                       "stroke": "none", "cornerType": "round",
                                                       "corners": 0},
                                        "padding": {"left": 5, "top": 0, "bottom": 0,
                                                    "right": 5}, "minFontSize": 8,
                                        "maxFontSize": 72,
                                        "adjustFontSize": {"width": False, "height": False},
                                        "fontSize": "11px",
                                        "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                        "fontColor": "#7c868e", "fontOpacity": 1,
                                        "fontDecoration": "none", "fontStyle": "normal",
                                        "fontVariant": "normal", "fontWeight": "normal",
                                        "letterSpacing": "normal", "textDirection": "ltr",
                                        "lineHeight": "normal", "textIndent": 0,
                                        "vAlign": "top", "hAlign": "start",
                                        "wordWrap": "normal", "wordBreak": "normal",
                                        "textOverflow": "", "selectable": False,
                                        "disablePointerEvents": False, "useHtml": False,
                                        "position": "outside", "anchor": "center",
                                        "offsetX": 0, "offsetY": 0, "rotation": 0},
                        "ticks": {"zIndex": 35, "enabled": True, "stroke": "#CECECE",
                                  "length": 6, "position": "outside"},
                        "minorTicks": {"zIndex": 35, "enabled": False, "stroke": "#EAEAEA",
                                       "length": 4, "position": "outside"},
                        "stroke": "#CECECE", "staggerMode": False, "staggerLines": None,
                        "staggerMaxLines": 2, "width": 50, "orientation": "left",
                        "drawFirstLabel": True, "drawLastLabel": True,
                        "overlapMode": "no-overlap", "scale": 0}], "xGrids": [
                {"palette": {"type": "distinct", "items": ["none"]}, "zIndex": 11.001,
                 "enabled": True, "stroke": "#CECECE", "drawFirstLine": True,
                 "drawLastLine": True, "isMinor": False, "scale": 1}], "yGrids": [
                {"palette": {"type": "distinct", "items": ["none"]}, "zIndex": 11,
                 "enabled": True, "stroke": "#CECECE", "drawFirstLine": True,
                 "drawLastLine": True, "isMinor": False, "scale": 0}], "xMinorGrids": [
                {"palette": {"type": "distinct", "items": ["none"]}, "zIndex": 10.003,
                 "enabled": True, "stroke": "#EAEAEA", "drawFirstLine": True,
                 "drawLastLine": True, "isMinor": True, "scale": 1}], "yMinorGrids": [
                {"palette": {"type": "distinct", "items": ["none"]}, "zIndex": 10.002,
                 "enabled": True, "stroke": "#EAEAEA", "drawFirstLine": True,
                 "drawLastLine": True, "isMinor": True, "scale": 0}], "series": [
                {"enabled": True, "seriesType": "line", "clip": True, "meta": {},
                 "name": "EMA(20)", "color": None, "connectMissingPoints": False,
                 "isVertical": None,
                 "normal": {"stroke": {"color": "#455a64", "thickness": 1.5},
                            "hatchFill": "none", "risingHatchFill": "none",
                            "fallingHatchFill": "none", "labels": {"enabled": None,
                                                                   "background": {
                                                                       "enabled": False,
                                                                       "fill": "#ffffff",
                                                                       "stroke": "none",
                                                                       "cornerType": "round"},
                                                                   "padding": {"left": 4,
                                                                               "top": 4,
                                                                               "bottom": 4,
                                                                               "right": 4},
                                                                   "minFontSize": 8,
                                                                   "maxFontSize": 72,
                                                                   "adjustFontSize": {
                                                                       "width": False,
                                                                       "height": False},
                                                                   "fontSize": 12,
                                                                   "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                                                   "fontColor": "#7c868e",
                                                                   "fontOpacity": 1,
                                                                   "fontDecoration": "none",
                                                                   "fontStyle": "normal",
                                                                   "fontVariant": "normal",
                                                                   "fontWeight": "normal",
                                                                   "letterSpacing": "normal",
                                                                   "textDirection": "ltr",
                                                                   "lineHeight": "normal",
                                                                   "textIndent": 0,
                                                                   "vAlign": "top",
                                                                   "hAlign": "start",
                                                                   "wordWrap": "normal",
                                                                   "wordBreak": "normal",
                                                                   "textOverflow": "",
                                                                   "selectable": False,
                                                                   "disablePointerEvents": False,
                                                                   "useHtml": False,
                                                                   "position": "value",
                                                                   "anchor": "auto",
                                                                   "offsetX": 0, "offsetY": 10,
                                                                   "rotation": 0,
                                                                   "width": None,
                                                                   "height": None,
                                                                   "clip": None},
                            "minLabels": {"enabled": None}, "maxLabels": {"enabled": None},
                            "markers": {"enabled": False, "disablePointerEvents": False,
                                        "position": "value", "anchor": "center", "offsetX": 0,
                                        "offsetY": 0, "rotation": 0, "size": 4},
                            "outlierMarkers": {"enabled": None}},
                 "hovered": {"hatchFill": "none", "risingHatchFill": "none",
                             "fallingHatchFill": "none", "labels": {"enabled": None},
                             "minLabels": {"enabled": None}, "maxLabels": {"enabled": None},
                             "markers": {"enabled": None, "size": 6},
                             "outlierMarkers": {"enabled": None}},
                 "selected": {"fill": {"color": "#333", "opacity": 0.85},
                              "negativeFill": {"color": "#333", "opacity": 0.85},
                              "risingFill": {"color": "#333", "opacity": 0.85},
                              "fallingFill": {"color": "#333", "opacity": 0.85},
                              "stroke": {"color": "#333", "opacity": 0.85},
                              "lowStroke": {"color": "#333", "opacity": 0.85},
                              "highStroke": {"color": "#333", "opacity": 0.85},
                              "lowFill": {"color": "#333", "opacity": 0.85},
                              "highFill": {"color": "#333", "opacity": 0.85},
                              "negativeStroke": {"color": "#333", "opacity": 0.85},
                              "risingStroke": {"color": "#333", "opacity": 0.85},
                              "fallingStroke": {"color": "#333", "opacity": 0.85},
                              "hatchFill": "none", "risingHatchFill": "none",
                              "fallingHatchFill": "none", "labels": {"enabled": None},
                              "minLabels": {"enabled": None}, "maxLabels": {"enabled": None},
                              "markers": {"enabled": None, "size": 6,
                                          "fill": {"color": "#333", "opacity": 0.85},
                                          "stroke": {"color": "#212121", "thickness": 1.5}},
                              "outlierMarkers": {"enabled": None}}, "a11y": {"enabled": False,
                                                                             "titleFormat": "Series named {%SeriesName} with {%SeriesPointsCount} points. Min value is {%SeriesYMin}, max value is {%SeriesYMax}"},
                 "yScale": 0},
                {"enabled": True, "seriesType": "candlestick", "clip": True, "meta": {},
                 "name": "CSCO", "color": None, "pointWidth": "75%", "isVertical": None,
                 "normal": {"risingFill": "#64b5f6", "fallingFill": "#ef6c00",
                            "risingStroke": "#64b5f6", "fallingStroke": "#ef6c00",
                            "hatchFill": "none", "risingHatchFill": "none",
                            "fallingHatchFill": "none", "labels": {"enabled": None,
                                                                   "background": {
                                                                       "enabled": False,
                                                                       "fill": "#ffffff",
                                                                       "stroke": "none",
                                                                       "cornerType": "round"},
                                                                   "padding": {"left": 4,
                                                                               "top": 4,
                                                                               "bottom": 4,
                                                                               "right": 4},
                                                                   "minFontSize": 8,
                                                                   "maxFontSize": 72,
                                                                   "adjustFontSize": {
                                                                       "width": False,
                                                                       "height": False},
                                                                   "fontSize": 12,
                                                                   "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                                                   "fontColor": "#7c868e",
                                                                   "fontOpacity": 1,
                                                                   "fontDecoration": "none",
                                                                   "fontStyle": "normal",
                                                                   "fontVariant": "normal",
                                                                   "fontWeight": "normal",
                                                                   "letterSpacing": "normal",
                                                                   "textDirection": "ltr",
                                                                   "lineHeight": "normal",
                                                                   "textIndent": 0,
                                                                   "vAlign": "top",
                                                                   "hAlign": "start",
                                                                   "wordWrap": "normal",
                                                                   "wordBreak": "normal",
                                                                   "textOverflow": "",
                                                                   "selectable": False,
                                                                   "disablePointerEvents": False,
                                                                   "useHtml": False,
                                                                   "position": "high",
                                                                   "anchor": "auto",
                                                                   "offsetX": 0, "offsetY": 10,
                                                                   "rotation": 0,
                                                                   "width": None,
                                                                   "height": None,
                                                                   "clip": None},
                            "minLabels": {"enabled": None}, "maxLabels": {"enabled": None},
                            "markers": {"enabled": False, "disablePointerEvents": False,
                                        "position": "high", "anchor": "center", "offsetX": 0,
                                        "offsetY": 0, "rotation": 0, "size": 4},
                            "outlierMarkers": {"enabled": None}},
                 "hovered": {"hatchFill": "none", "risingHatchFill": "none",
                             "fallingHatchFill": "none", "labels": {"enabled": None},
                             "minLabels": {"enabled": None}, "maxLabels": {"enabled": None},
                             "markers": {"enabled": None, "size": 6},
                             "outlierMarkers": {"enabled": None}},
                 "selected": {"fill": {"color": "#333", "opacity": 0.85},
                              "negativeFill": {"color": "#333", "opacity": 0.85},
                              "risingFill": {"color": "#333", "opacity": 0.85},
                              "fallingFill": {"color": "#333", "opacity": 0.85},
                              "stroke": {"color": "#333", "opacity": 0.85},
                              "lowStroke": {"color": "#333", "opacity": 0.85},
                              "highStroke": {"color": "#333", "opacity": 0.85},
                              "lowFill": {"color": "#333", "opacity": 0.85},
                              "highFill": {"color": "#333", "opacity": 0.85},
                              "negativeStroke": {"color": "#333", "opacity": 0.85},
                              "risingStroke": {"color": "#333", "opacity": 0.85},
                              "fallingStroke": {"color": "#333", "opacity": 0.85},
                              "hatchFill": "none", "risingHatchFill": "none",
                              "fallingHatchFill": "none", "labels": {"enabled": None},
                              "minLabels": {"enabled": None}, "maxLabels": {"enabled": None},
                              "markers": {"enabled": None, "size": 6,
                                          "fill": {"color": "#333", "opacity": 0.85},
                                          "stroke": {"color": "#212121", "thickness": 1.5}},
                              "outlierMarkers": {"enabled": None}}, "a11y": {"enabled": False,
                                                                             "titleFormat": "Series named {%SeriesName} with {%SeriesPointsCount} points. Min value is {%SeriesYMin}, max value is {%SeriesYMax}"},
                 "yScale": 0}], "scales": [
                {"type": "linear", "inverted": False, "maximum": None, "minimum": None,
                 "minimumGap": 0.1, "maximumGap": 0.1, "softMinimum": None,
                 "softMaximum": None, "alignMinimum": True, "alignMaximum": True,
                 "maxTicksCount": 1000,
                 "ticks": {"mode": "linear", "base": 0, "allowFractional": True, "minCount": 4,
                           "maxCount": 6},
                 "minorTicks": {"mode": "linear", "base": 0, "allowFractional": True,
                                "count": 5}, "stackMode": "none", "stackDirection": "direct",
                 "stickToZero": True, "comparisonMode": "none"}, {}]}],
            "crosshair": {"enabled": True, "xStroke": "#969EA5", "yStroke": "#969EA5",
                          "displayMode": "sticky", "xLabels": [
                    {"enabled": True, "fontSize": 12,
                     "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                     "fontColor": "#ffffff", "fontOpacity": 1, "fontDecoration": "none",
                     "fontStyle": "normal", "fontVariant": "normal", "fontWeight": 400,
                     "letterSpacing": "normal", "textDirection": "ltr", "lineHeight": "normal",
                     "textIndent": 0, "vAlign": "top", "hAlign": "start", "wordWrap": "normal",
                     "wordBreak": "normal", "textOverflow": "", "selectable": False,
                     "disablePointerEvents": True, "useHtml": False, "text": "Label text",
                     "width": None, "height": None, "anchor": None, "offsetX": 0, "offsetY": 0,
                     "rotation": 0, "adjustFontSize": {"width": False, "height": False},
                     "minFontSize": 8, "maxFontSize": 16,
                     "background": {"zIndex": 0, "enabled": True,
                                    "fill": {"color": "#212121", "opacity": 0.7},
                                    "stroke": "none", "disablePointerEvents": True,
                                    "cornerType": "round"},
                     "padding": {"left": 10, "top": 5, "bottom": 5, "right": 10},
                     "axisIndex": 0}], "yLabels": [{"enabled": True, "fontSize": 12,
                                                    "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                                    "fontColor": "#ffffff", "fontOpacity": 1,
                                                    "fontDecoration": "none",
                                                    "fontStyle": "normal",
                                                    "fontVariant": "normal", "fontWeight": 400,
                                                    "letterSpacing": "normal",
                                                    "textDirection": "ltr",
                                                    "lineHeight": "normal", "textIndent": 0,
                                                    "vAlign": "top", "hAlign": "start",
                                                    "wordWrap": "normal",
                                                    "wordBreak": "normal", "textOverflow": "",
                                                    "selectable": False,
                                                    "disablePointerEvents": True,
                                                    "useHtml": False, "text": "Label text",
                                                    "width": None, "height": None,
                                                    "anchor": None, "offsetX": 0, "offsetY": 0,
                                                    "rotation": 0,
                                                    "adjustFontSize": {"width": False,
                                                                       "height": False},
                                                    "minFontSize": 8, "maxFontSize": 16,
                                                    "background": {"zIndex": 0,
                                                                   "enabled": True,
                                                                   "fill": {"color": "#212121",
                                                                            "opacity": 0.7},
                                                                   "stroke": "none",
                                                                   "disablePointerEvents": True,
                                                                   "cornerType": "round"},
                                                    "padding": {"left": 10, "top": 5,
                                                                "bottom": 5, "right": 10},
                                                    "axisIndex": 0}]},
            "eventMarkers": {"direction": "auto", "position": "axis", "seriesId": "0",
                             "fieldName": "value",
                             "normal": {"type": "circle", "width": 22, "height": 22,
                                        "fill": "#515151", "stroke": "#515151", "format": "A",
                                        "fontPadding": 2, "minFontSize": 6, "maxFontSize": 20,
                                        "adjustFontSize": {"width": True, "height": True},
                                        "fontSize": None,
                                        "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                        "fontColor": "#fff", "fontOpacity": 1,
                                        "fontDecoration": "none", "fontStyle": "normal",
                                        "fontVariant": "normal", "fontWeight": "normal",
                                        "letterSpacing": "normal", "textDirection": "ltr",
                                        "lineHeight": "normal", "textIndent": 0,
                                        "vAlign": "middle", "hAlign": "center",
                                        "wordWrap": "normal", "wordBreak": "normal",
                                        "textOverflow": "", "selectable": False,
                                        "disablePointerEvents": False, "useHtml": False,
                                        "connector": {"stroke": "#455a64", "length": 5}},
                             "hovered": {"connector": {}},
                             "selected": {"fill": "#dd2c00", "connector": {}},
                             "tooltip": {"zIndex": 0, "enabled": True, "minFontSize": 9,
                                         "maxFontSize": 13,
                                         "adjustFontSize": {"width": False, "height": False},
                                         "fontSize": 12,
                                         "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                         "fontColor": "#fff", "fontOpacity": 1,
                                         "fontDecoration": "none", "fontStyle": "normal",
                                         "fontVariant": "normal", "fontWeight": "normal",
                                         "letterSpacing": "normal", "textDirection": "ltr",
                                         "lineHeight": "normal", "textIndent": 0,
                                         "vAlign": "top", "hAlign": "start",
                                         "wordWrap": "normal", "wordBreak": "normal",
                                         "textOverflow": "", "selectable": False,
                                         "disablePointerEvents": False, "useHtml": False,
                                         "width": None, "height": None,
                                         "unionFormat": "{%joinedFormattedValues}",
                                         "valuePrefix": "", "valuePostfix": "",
                                         "position": "left-top", "anchor": "left-top",
                                         "offsetX": 10, "offsetY": 10,
                                         "allowLeaveScreen": False, "allowLeaveChart": True,
                                         "allowLeaveStage": False,
                                         "title": {"zIndex": 1, "enabled": True,
                                                   "fontSize": 14,
                                                   "fontFamily": "Verdana, Helvetica, Arial, sans-serif",
                                                   "fontColor": "#fff", "fontOpacity": 1,
                                                   "fontDecoration": "none",
                                                   "fontStyle": "normal",
                                                   "fontVariant": "normal",
                                                   "fontWeight": "normal",
                                                   "letterSpacing": "normal",
                                                   "textDirection": "ltr",
                                                   "lineHeight": "normal", "textIndent": 0,
                                                   "vAlign": "top", "hAlign": "left",
                                                   "wordWrap": "normal", "wordBreak": "normal",
                                                   "textOverflow": "", "selectable": False,
                                                   "disablePointerEvents": False,
                                                   "useHtml": False, "width": None,
                                                   "height": None, "align": "left",
                                                   "orientation": "top", "rotation": 0,
                                                   "text": "", "background": {"enabled": False,
                                                                              "fill": "none",
                                                                              "stroke": "none",
                                                                              "cornerType": "round",
                                                                              "corners": 0}},
                                         "separator": {"zIndex": 1, "enabled": True,
                                                       "fill": {"color": "#CECECE",
                                                                "opacity": 0.3},
                                                       "stroke": "none", "width": "100%",
                                                       "height": 1, "orientation": "top",
                                                       "margin": {"left": 0, "top": 5,
                                                                  "bottom": 5, "right": 0}},
                                         "background": {"zIndex": 0, "enabled": True,
                                                        "fill": {"color": "#212121",
                                                                 "opacity": 0.7},
                                                        "stroke": "none",
                                                        "cornerType": "round"},
                                         "padding": {"left": 10, "top": 5, "bottom": 5,
                                                     "right": 10}, "hideDelay": 0}},
            "zoomMarqueeFill": {"color": "#d3d3d3", "opacity": 0.4},
            "zoomMarqueeStroke": "#d3d3d3",
            "interactivity": {"hoverMode": "single", "selectionMode": "multi-select",
                              "spotRadius": 2, "allowMultiSeriesSelection": True,
                              "multiSelectOnClick": False, "unselectOnClickOutOfPoint": True,
                              "zoomOnMouseWheel": False, "scrollOnMouseWheel": False}
        }}
    return render_template("index.html", title="Anychart Python template", chartData=json.dumps(chart))


if __name__ == "__main__":
    app.run()
